name: Preview URL on Branch Push
on:
  push:
    branches:
      - '**'  # Run on all branches except the main branch
    paths-ignore:
      - 'README.md'

jobs:
  notify-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Vercel Preview URL
        run: |
          echo "Preview URL: https://$GITHUB_REF_NAME--your-project-name.vercel.app"
